#!/usr/bin/env bash

IMAGE_NAME=eg-todo-list
REST_SERVER=https://rest.$DOMAIN

npm ci

npx esbuild src/index.jsx --define:process.env.REST_SERVER=\"$REST_SERVER\" --bundle --outfile=build.js --minify --sourcemap

docker build . --file Dockerfile --tag $IMAGE_NAME

IMAGE_ID=$DOCKER_REGISTRY_URL_PREFIX/$IMAGE_NAME

# Change all uppercase to lowercase
IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
# Strip git ref prefix from version
IMAGE_TAG=$GITHUB_SHA
echo IMAGE_ID=$IMAGE_ID
echo IMAGE_TAG=$IMAGE_TAG
docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_TAG
docker push $IMAGE_ID:$IMAGE_TAG